import = ["/home/jason/.config/alacritty/rose-pine.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14

[shell]
args = ["--login", "--init-command", "tmux", "clear"]
program = "/usr/bin/fish"

[window]
opacity = 0.99

[window.padding]
x = 10
y = 10
