
[env]
TERM = "xterm-256color"

[font]
size = 10 
normal = { family = "monospace", style = "Regular" }
bold = { family = "monospace", style = "Bold" }

[terminal.shell]
args = ["--login", "--init-command", "tmux", "clear"]
program = "/usr/bin/fish"

[window]
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10

[general]
import = ["/home/jason/.config/alacritty/rose-pine.toml"]

[terminal]
