local ok, palette = pcall(require, 'settings.colors')

if not ok then
  return
end

vim.cmd.colorscheme('rose-pine')
vim.cmd.highlight('normal guibg=none')

-- Get all highlights: so $VIMRUNTIME/syntax/hitest.vim
local highlight_groups = {
  --- Blank line indent
  ['ibl.indent.char.1'] = { fg = palette.cyan },
  -- Telescope
  NormalNC = { bg = palette.none },
  TelescopeNormal = { bg = palette.none },
  TelescopeBorder = { bg = palette.none },
  TelescopePreviewBorder = { fg = palette.none, bg = palette.none },
  TelescopePreviewNormal = { bg = palette.none },
  TelescopePreviewTitle = { fg = palette.none },
  TelescopePromptBorder = { fg = palette.bg_darker, bg = palette.bg_darker },
  TelescopePromptNormal = { bg = palette.bg_darker },
  TelescopePromptTitle = { fg = palette.bg_darker },
  TelescopeResultsBorder = { fg = palette.bg, bg = palette.bg },
  TelescopeResultsNormal = { bg = palette.bg },
  TelescopeResultsTitle = { fg = palette.bg },
  -- This one is for lsp suggestion menue
  Pmenu = { fg = palette.fg_med, bg = palette.none },
  -- Bufferline
  BufferLineBufferSelected = { bg = palette.bg_darker, fg = palette.fg },
  BufferLineFill = { bg = palette.none },
  BufferLineTab = { bg = palette.none },

  BufferLineOffsetSeparator = { bg = palette.none, fg = palette.none },
  BufferLinePickVisible = { bg = palette.none },
  BufferLinePickSelected = { bg = palette.bg_darker },
  BufferLineIndicatorVisible = { bg = palette.none },
  BufferLineIndicatorSelected = { bg = palette.green, fg = palette.bg },
  BufferLineTabSeparatorSelected = { bg = palette.bg_darker },
  BufferLineTabSeparator = { bg = palette.none },
  BufferLineError = { bg = palette.none, fg = palette.red },
  BufferLineSeparatorSelected = { bg = palette.bg_darker },
  BufferLineDuplicate = { bg = palette.none },
  BufferLineDuplicateVisible = { bg = palette.none },
  BufferLineDuplicateSelected = { bg = palette.bg_darker },
  BufferLineModifiedSelected = { bg = palette.bg_darker, fg = palette.yellow },
  BufferLineModifiedVisible = { bg = palette.none },
  BufferLineErrorDiagnosticSelected = { bg = palette.bg_darker },
  BufferLineErrorDiagnosticVisible = { bg = palette.none },
  BufferLineErrorDiagnostic = { bg = palette.none },
  BufferLineErrorSelected = { bg = palette.bg_darker },
  BufferLineErrorVisible = { bg = palette.none },
  BufferLineWarningDiagnosticSelected = { bg = palette.bg_darker },
  BufferLineTabClose = { bg = palette.none },
  BufferLineTabSelected = { bg = palette.bg_darker },
  BufferLineGroupLabel = { bg = palette.none },
  BufferLineGroupSeparator = { bg = palette.none },
  BufferLineTruncMarker = { bg = palette.none },
  BufferLineInfoDiagnostic = { bg = palette.none },
  BufferLineInfo = { bg = palette.none },
  BufferLineInfoVisible = { bg = palette.none },
  BufferLineBuffer = { bg = palette.none },
  BufferLineHintDiagnosticVisible = { bg = palette.none },
  BufferLineHintDiagnostic = { bg = palette.none },
  BufferLineHintSelected = { bg = palette.bg_darker },
  BufferLineHintVisible = { bg = palette.none },
  BufferLineDiagnosticSelected = { bg = palette.bg_darker },
  BufferLineDiagnosticVisible = { bg = palette.none },
  BufferLineNumbersVisible = { bg = palette.none },
  BufferLineNumbersSelected = { bg = palette.bg_darker },
  BufferLineNumbers = { bg = palette.none },
  BufferLineBufferVisible = { bg = palette.none },
  BufferLineCloseButtonSelected = { bg = palette.bg_darker },
  BufferLineCloseButtonVisible = { bg = palette.none },
  BufferLineSeparator = { bg = palette.none, fg = palette.bg_light },
  BufferLineHint = { bg = palette.none },
  BufferLineCloseButton = { bg = palette.none },
  BufferLineDiagnostic = { bg = palette.none },
  BufferLineBackground = { bg = palette.none },
  BufferLineHintDiagnosticSelected = { bg = palette.bg_darker },
  BufferLineInfoSelected = { bg = palette.bg_darker },
  BufferLineInfoDiagnosticVisible = { bg = palette.none },
  BufferLineWarningVisible = { bg = palette.none },
  BufferLineInfoDiagnosticSelected = { bg = palette.bg_darker },
  BufferLineWarning = { bg = palette.none },
  BufferLinePick = { bg = palette.none },
  BufferLineWarningSelected = { bg = palette.bg_darker },
  BufferLineWarningDiagnostic = { bg = palette.none },
  BufferLineWarningDiagnosticVisible = { bg = palette.none },
  BufferLineModified = { bg = palette.none, fg = palette.yellow },
  BufferLineSeparatorVisible = { bg = palette.none },

  -- Lualine
  -- vim.api.nvim_set_hl(0, name, value)
  -- lualine_c_mode_normal = { fg = palette.fg_med, bold = true },
  -- lualine_c_mode_insert = { fg = palette.magenta, bold = true },
  -- lualine_c_mode_visual = { fg = palette.yellow, bold = true },
  -- lualine_c_mode_replace = { fg = palette.magenta, bold = true },
  -- lualine_c_mode_command = { fg = palette.red, bold = true },
  -- lualine_c_mode_terminal = { fg = palette.blue, bold = true },
  -- lualine_c_mode_inactive = { fg = palette.subtle, bold = true },
  -- lualine_c_progress_normal = { bg = palette.fg_med, fg = palette.bg_darker },
  -- lualine_c_progress_insert = { bg = palette.magenta, fg = palette.bg_darker },
  -- lualine_c_progress_visual = { bg = palette.yellow, fg = palette.bg_darker },
  -- lualine_c_progress_replace = { bg = palette.magenta, fg = palette.bg_darker },
  -- lualine_c_progress_command = { bg = palette.red, fg = palette.bg_darker },
  -- lualine_c_progress_terminal = { bg = palette.blue, fg = palette.bg_darker },
  -- lualine_c_progress_inactive = { bg = palette.subtle, fg = palette.bg_darker },
  -- lualine_c_filename_normal = { fg = palette.fg },
  -- lualine_c_filename_insert = { fg = palette.fg },
  -- lualine_c_filename_visual = { fg = palette.fg },
  -- lualine_c_filename_replace = { fg = palette.fg },
  -- lualine_c_filename_command = { fg = palette.fg },
  -- lualine_c_filename_terminal = { fg = palette.fg },
  -- lualine_c_filename_inactive = { fg = palette.fg },
  -- lualine_c_diagnostics_error_normal = { fg = palette.red },
  -- lualine_c_diagnostics_error_insert = { fg = palette.red },
  -- lualine_c_diagnostics_error_visual = { fg = palette.red },
  -- lualine_c_diagnostics_error_replace = { fg = palette.red },
  -- lualine_c_diagnostics_error_command = { fg = palette.red },
  -- lualine_c_diagnostics_error_terminal = { fg = palette.red },
  -- lualine_c_diagnostics_error_inactive = { fg = palette.red },
  -- lualine_c_diagnostics_warn_normal = { fg = palette.yellow },
  -- lualine_c_diagnostics_warn_insert = { fg = palette.yellow },
  -- lualine_c_diagnostics_warn_visual = { fg = palette.yellow },
  -- lualine_c_diagnostics_warn_replace = { fg = palette.yellow },
  -- lualine_c_diagnostics_warn_command = { fg = palette.yellow },
  -- lualine_c_diagnostics_warn_terminal = { fg = palette.yellow },
  -- lualine_c_diagnostics_warn_inactive = { fg = palette.yellow },
  -- lualine_c_diagnostics_info_normal = { fg = palette.blue },
  -- lualine_c_diagnostics_info_insert = { fg = palette.blue },
  -- lualine_c_diagnostics_info_visual = { fg = palette.blue },
  -- lualine_c_diagnostics_info_replace = { fg = palette.blue },
  -- lualine_c_diagnostics_info_command = { fg = palette.blue },
  -- lualine_c_diagnostics_info_terminal = { fg = palette.blue },
  -- lualine_c_diagnostics_info_inactive = { fg = palette.blue },
  -- lualine_c_diagnostics_hint_normal = { fg = palette.green },
  -- lualine_c_diagnostics_hint_insert = { fg = palette.green },
  -- lualine_c_diagnostics_hint_visual = { fg = palette.green },
  -- lualine_c_diagnostics_hint_replace = { fg = palette.green },
  -- lualine_c_diagnostics_hint_command = { fg = palette.green },
  -- lualine_c_diagnostics_hint_terminal = { fg = palette.green },
  -- lualine_c_diagnostics_hint_inactive = { fg = palette.green },
  -- lualine_x_diff_added_normal = { fg = palette.green },
  -- lualine_x_diff_added_insert = { fg = palette.green },
  -- lualine_x_diff_added_visual = { fg = palette.green },
  -- lualine_x_diff_added_replace = { fg = palette.green },
  -- lualine_x_diff_added_command = { fg = palette.green },
  -- lualine_x_diff_added_terminal = { fg = palette.green },
  -- lualine_x_diff_added_inactive = { fg = palette.green },
  -- lualine_x_diff_modified_normal = { fg = palette.yellow },
  -- lualine_x_diff_modified_insert = { fg = palette.yellow },
  -- lualine_x_diff_modified_visual = { fg = palette.yellow },
  -- lualine_x_diff_modified_replace = { fg = palette.yellow },
  -- lualine_x_diff_modified_command = { fg = palette.yellow },
  -- lualine_x_diff_modified_terminal = { fg = palette.yellow },
  -- lualine_x_diff_modified_inactive = { fg = palette.yellow },
  -- lualine_x_diff_removed_normal = { fg = palette.red },
  -- lualine_x_diff_removed_insert = { fg = palette.red },
  -- lualine_x_diff_removed_visual = { fg = palette.red },
  -- lualine_x_diff_removed_replace = { fg = palette.red },
  -- lualine_x_diff_removed_command = { fg = palette.red },
  -- lualine_x_diff_removed_terminal = { fg = palette.red },
  -- lualine_x_diff_removed_inactive = { fg = palette.red },
  -- lualine_x_branch_normal = { fg = palette.cyan, bold = true },
  -- lualine_x_branch_insert = { fg = palette.cyan, bold = true },
  -- lualine_x_branch_visual = { fg = palette.cyan, bold = true },
  -- lualine_x_branch_replace = { fg = palette.cyan, bold = true },
  -- lualine_x_branch_command = { fg = palette.cyan, bold = true },
  -- lualine_x_branch_terminal = { fg = palette.cyan, bold = true },
  -- lualine_x_branch_inactive = { fg = palette.cyan, bold = true }
}


require('utils').set_highlight_groups(highlight_groups)
