local ok, bluloco = pcall(require, 'bluloco')

if not ok then
  return
end

bluloco.setup({
  style = 'dark',
  italics = true,
  transparent = true,
})

-- Suggested terminal bg #1F2229
local palette = {
  bg_darker = '#1b1e24',
  bg = '#282C34',
  bg_light = '#282d36',
  fg_med = '#abb2bf',
  fg = '#8691A3',
  red = '#FF6480',
  yellow = '#f6c177',
  cyan = '#3691FF',
  green = '#3FC56B',
  blue = '#10B1FE',
  magenta = '#9F7EFE',
  none = 'NONE',
}

local highlight_groups = {
  -- Telescope
  TelescopeNormal = { bg = palette.none },
  TelescopeBorder = { bg = palette.none },
  TelescopePreviewBorder = { fg = palette.none, bg = palette.none },
  TelescopePreviewNormal = { fg = palette.none, bg = palette.none },
  NormalFloat = { bg = palette.none },
  TelescopePreviewTitle = { fg = palette.none },
  TelescopePromptBorder = { fg = palette.bg_darker, bg = palette.bg_darker },
  TelescopePromptNormal = { bg = palette.bg_darker },
  TelescopePromptTitle = { fg = palette.bg_darker },
  TelescopeResultsBorder = { fg = palette.bg, bg = palette.bg },
  TelescopeResultsNormal = { bg = palette.bg },
  TelescopeResultsTitle = { fg = palette.bg },
  -- This one is for lsp suggestion menue
  Pmenu = { fg = palette.fg_med, bg = palette.none },
  -- Lualine
  lualine_c_mode_normal = { fg = palette.fg, bold = true },
  lualine_c_mode_insert = { fg = palette.yellow, bold = true },
  lualine_c_mode_visual = { fg = palette.green, bold = true },
  lualine_c_mode_replace = { fg = palette.magenta, bold = true },
  lualine_c_mode_command = { fg = palette.red, bold = true },
  lualine_c_mode_terminal = { fg = palette.blue, bold = true },
  lualine_c_mode_inactive = { fg = palette.subtle, bold = true },
  lualine_c_progress_normal = { fg = palette.fg },
  lualine_c_progress_insert = { fg = palette.fg },
  lualine_c_progress_visual = { fg = palette.fg },
  lualine_c_progress_replace = { fg = palette.fg },
  lualine_c_progress_command = { fg = palette.fg },
  lualine_c_progress_terminal = { fg = palette.fg },
  lualine_c_progress_inactive = { fg = palette.fg },
  lualine_c_filename_normal = { fg = palette.blue },
  lualine_c_filename_insert = { fg = palette.blue },
  lualine_c_filename_visual = { fg = palette.blue },
  lualine_c_filename_replace = { fg = palette.blue },
  lualine_c_filename_command = { fg = palette.blue },
  lualine_c_filename_terminal = { fg = palette.blue },
  lualine_c_filename_inactive = { fg = palette.blue },
  lualine_c_diagnostics_error_normal = { fg = palette.red },
  lualine_c_diagnostics_error_insert = { fg = palette.red },
  lualine_c_diagnostics_error_visual = { fg = palette.red },
  lualine_c_diagnostics_error_replace = { fg = palette.red },
  lualine_c_diagnostics_error_command = { fg = palette.red },
  lualine_c_diagnostics_error_terminal = { fg = palette.red },
  lualine_c_diagnostics_error_inactive = { fg = palette.red },
  lualine_c_diagnostics_warn_normal = { fg = palette.yellow },
  lualine_c_diagnostics_warn_insert = { fg = palette.yellow },
  lualine_c_diagnostics_warn_visual = { fg = palette.yellow },
  lualine_c_diagnostics_warn_replace = { fg = palette.yellow },
  lualine_c_diagnostics_warn_command = { fg = palette.yellow },
  lualine_c_diagnostics_warn_terminal = { fg = palette.yellow },
  lualine_c_diagnostics_warn_inactive = { fg = palette.yellow },
  lualine_c_diagnostics_info_normal = { fg = palette.blue },
  lualine_c_diagnostics_info_insert = { fg = palette.blue },
  lualine_c_diagnostics_info_visual = { fg = palette.blue },
  lualine_c_diagnostics_info_replace = { fg = palette.blue },
  lualine_c_diagnostics_info_command = { fg = palette.blue },
  lualine_c_diagnostics_info_terminal = { fg = palette.blue },
  lualine_c_diagnostics_info_inactive = { fg = palette.blue },
  lualine_c_diagnostics_hint_normal = { fg = palette.green },
  lualine_c_diagnostics_hint_insert = { fg = palette.green },
  lualine_c_diagnostics_hint_visual = { fg = palette.green },
  lualine_c_diagnostics_hint_replace = { fg = palette.green },
  lualine_c_diagnostics_hint_command = { fg = palette.green },
  lualine_c_diagnostics_hint_terminal = { fg = palette.green },
  lualine_c_diagnostics_hint_inactive = { fg = palette.green },
  lualine_x_diff_added_normal = { fg = palette.green },
  lualine_x_diff_added_insert = { fg = palette.green },
  lualine_x_diff_added_visual = { fg = palette.green },
  lualine_x_diff_added_replace = { fg = palette.green },
  lualine_x_diff_added_command = { fg = palette.green },
  lualine_x_diff_added_terminal = { fg = palette.green },
  lualine_x_diff_added_inactive = { fg = palette.green },
  lualine_x_diff_modified_normal = { fg = palette.yellow },
  lualine_x_diff_modified_insert = { fg = palette.yellow },
  lualine_x_diff_modified_visual = { fg = palette.yellow },
  lualine_x_diff_modified_replace = { fg = palette.yellow },
  lualine_x_diff_modified_command = { fg = palette.yellow },
  lualine_x_diff_modified_terminal = { fg = palette.yellow },
  lualine_x_diff_modified_inactive = { fg = palette.yellow },
  lualine_x_diff_removed_normal = { fg = palette.red },
  lualine_x_diff_removed_insert = { fg = palette.red },
  lualine_x_diff_removed_visual = { fg = palette.red },
  lualine_x_diff_removed_replace = { fg = palette.red },
  lualine_x_diff_removed_command = { fg = palette.red },
  lualine_x_diff_removed_terminal = { fg = palette.red },
  lualine_x_diff_removed_inactive = { fg = palette.red },
  lualine_x_branch_normal = { fg = palette.cyan },
  lualine_x_branch_insert = { fg = palette.cyan },
  lualine_x_branch_visual = { fg = palette.cyan },
  lualine_x_branch_replace = { fg = palette.cyan },
  lualine_x_branch_command = { fg = palette.cyan },
  lualine_x_branch_terminal = { fg = palette.cyan },
  lualine_x_branch_inactive = { fg = palette.cyan }
}

vim.cmd.colorscheme('bluloco')
vim.cmd.highlight('normal guibg=none')
require('utils').set_highlight_groups(highlight_groups)
